### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by baptooo** [ekino/webpack-plugin-assets-to-map#2]
Hey @Rambobafet,

just some advices about your documentation:

## Add a summary

- [Main goal](#main-goal)
- [What for](#what-for)
- [etc.](#etc)

## Missing installation part

Could be in **How to use ?**
```sh
$ npm install --save-dev webpack-plugin-assets-to-map
```

## Options

Enhance visibility

**sourcePath** - `{String}` (default: `""`)
Where to find the assets you need to put in the Json file

**files** - `{Object}` (default: `{ key: "name" }`)
key will be used as the key in the generated json file...

Greetings

**Comment by Rambobafet** [comment]
Thanks :)
README.md edited in 9b2e8e9e97e4147252d60861f48a7f96f1dbbe3c

**Comment by baptooo** [comment]
Thanks <3
